// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package rate

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ServerServiceClient is the client API for ServerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ServerServiceClient interface {
	// Fetch Growth Records
	//
	// Fetch all Growth record data saved in five minutes interval
	GetGrowthRecords(ctx context.Context, in *ServerRequest, opts ...grpc.CallOption) (*Response, error)
	// Fetch Raw Growth Records
	//
	// Fetch all Raw Growth record data saved in five minutes interval
	GetRawGrowthRecords(ctx context.Context, in *ServerRequest, opts ...grpc.CallOption) (*RawResponse, error)
}

type serverServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewServerServiceClient(cc grpc.ClientConnInterface) ServerServiceClient {
	return &serverServiceClient{cc}
}

func (c *serverServiceClient) GetGrowthRecords(ctx context.Context, in *ServerRequest, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/rate.ServerService/GetGrowthRecords", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serverServiceClient) GetRawGrowthRecords(ctx context.Context, in *ServerRequest, opts ...grpc.CallOption) (*RawResponse, error) {
	out := new(RawResponse)
	err := c.cc.Invoke(ctx, "/rate.ServerService/GetRawGrowthRecords", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ServerServiceServer is the server API for ServerService service.
// All implementations must embed UnimplementedServerServiceServer
// for forward compatibility
type ServerServiceServer interface {
	// Fetch Growth Records
	//
	// Fetch all Growth record data saved in five minutes interval
	GetGrowthRecords(context.Context, *ServerRequest) (*Response, error)
	// Fetch Raw Growth Records
	//
	// Fetch all Raw Growth record data saved in five minutes interval
	GetRawGrowthRecords(context.Context, *ServerRequest) (*RawResponse, error)
	mustEmbedUnimplementedServerServiceServer()
}

// UnimplementedServerServiceServer must be embedded to have forward compatible implementations.
type UnimplementedServerServiceServer struct {
}

func (UnimplementedServerServiceServer) GetGrowthRecords(context.Context, *ServerRequest) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetGrowthRecords not implemented")
}
func (UnimplementedServerServiceServer) GetRawGrowthRecords(context.Context, *ServerRequest) (*RawResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRawGrowthRecords not implemented")
}
func (UnimplementedServerServiceServer) mustEmbedUnimplementedServerServiceServer() {}

// UnsafeServerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ServerServiceServer will
// result in compilation errors.
type UnsafeServerServiceServer interface {
	mustEmbedUnimplementedServerServiceServer()
}

func RegisterServerServiceServer(s grpc.ServiceRegistrar, srv ServerServiceServer) {
	s.RegisterService(&ServerService_ServiceDesc, srv)
}

func _ServerService_GetGrowthRecords_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ServerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServerServiceServer).GetGrowthRecords(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rate.ServerService/GetGrowthRecords",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServerServiceServer).GetGrowthRecords(ctx, req.(*ServerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServerService_GetRawGrowthRecords_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ServerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServerServiceServer).GetRawGrowthRecords(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rate.ServerService/GetRawGrowthRecords",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServerServiceServer).GetRawGrowthRecords(ctx, req.(*ServerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ServerService_ServiceDesc is the grpc.ServiceDesc for ServerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ServerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "rate.ServerService",
	HandlerType: (*ServerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetGrowthRecords",
			Handler:    _ServerService_GetGrowthRecords_Handler,
		},
		{
			MethodName: "GetRawGrowthRecords",
			Handler:    _ServerService_GetRawGrowthRecords_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "server.proto",
}
